# Generated by Django 4.1 on 2023-01-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='plan',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
