# Generated by Django 4.1 on 2023-01-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='plan',
        ),
    ]
